### ISSUE TITLE
No longer builds due to extremely old version of SWC_Common

### ISSUE THREAD

**Issue by Dessix** [wingertge/artemis#3]
The SWC_Common library is 5 versions above the one being imported, and appears to attempt to access `serde` internals in a destructive manner:
```
   Compiling swc_common v0.5.9
error[E0603]: module `export` is private
   --> /home/dessix/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_common-0.5.9/src/pass.rs:3:12
    |
3   | use serde::export::PhantomData;
    |            ^^^^^^ private module
    |
note: the module `export` is defined here
   --> /home/dessix/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.124/src/lib.rs:276:5
    |
276 | use self::__private as export;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by wingertge** [comment]
I just kind of assumed no one used this anymore so I stopped putting work into it. I just did cargo update, fixed some deprecated imports that my stupid editor decided to use and upgraded the typescript formatter that was using `swc_common` by 33 versions (!) so it should all work now. The new version is published already.

**Comment by Dessix** [comment]
Thank you!
From what I can tell, this is the only graphql client with built-in caching in the Rust ecosystem, so it’ll be very helpful for my use case.
